[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]] # カラースキーマ
repo = 'morhetz/gruvbox'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme gruvbox
'''

#[[plugins]]
#repo = 'w0rp/ale'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'othree/html5.vim'
